routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;

Route::get('/', 'PostsController@index')->name('main');
Route::get('search', 'PostsController@search')->name('search');
Route::get('category/{id}', 'PostsController@category')->name('category');
Route::get('user/{id}', 'PostsController@user')->name('user');
Route::get('tag/{id}', 'PostsController@tag')->name('tag');
Route::get('users', 'UsersController@index')->name('users');
Route::get('api/post', 'PostsController@api')->name('api.post');
Route::get('api/post/all', 'PostsController@all');

Route::post('api/count/view', 'CountController@view');
Route::post('api/count/share', 'CountController@share');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('api/image', 'ImageController');
    Route::get('profile', 'ProfileController@show')->name('profile');
});

Route::get('post/{id}', ['as' => 'post', 'uses' => 'PostController@show']);

Route::resource('item', 'ItemController');
Route::get('items/{ids}', ['as' => 'catalog', 'uses' => 'CatalogController@index']);

Route::get('sitemap.xml', 'XmlController@sitemap');
Route::get('sync/{subject}/{id}', ['as' => 'sync.post', 'uses' => 'SyncController@index']);

Route::get('phpinfo', ['middleware' => 'auth', 'uses' => 'Admin\UtilitiesController@phpinfo']);

Route::group(['middleware' => 'auth', 'namespace' => 'Admin', 'prefix' => 'admin'], function()
{
    Route::resource('urls', 'UrlController');
    Route::post('urls/{id}/update', 'UrlController@update')->name('admin.urls.update');
    Route::get('urls/{id}/delete', 'UrlController@destroy')->name('admin.urls.destroy');
    
    Route::resource('users', 'UserController');
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('products', 'ProductController');
    Route::resource('shops', 'ShopController');
    Route::get('shops/{id}/price', 'ShopController@priceIndex')->name('admin.shops.price');
    Route::get('shops/{id}/price/update', 'ShopController@priceUpdate')->name('admin.shops.price.update');
    Route::get('shops/{id}/price/import', 'ShopController@priceImport')->name('admin.shops.price.import');

    Route::resource('tags', 'TagController');
    Route::post('tags/{id}/update', 'TagController@update')->name('admin.tags.update');

    Route::resource('images', 'ImageController');
});

Route::get('/{slug}', ['as' => 'slug','uses' => 'SlugController@index']);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Slugable;
use Cache;

class Category extends Model
{
    use Slugable;
    
    protected $table = 'categories';
    protected $appends = ['url'];
    protected $visible = ['id','title','url'];
    protected $fillable = [
        'title',
        'alias',
        'title2',
        'text',
        'description',
        'image_full',
        'state',
        'parent_id',
        'order',
    ];
    
    public function posts()
    {
        return $this->hasMany('App\Post','category_id');
    }

    public function parent()
    {
        return $this->belongsTo('App\Category');
    }
	
    public static function ids($category_id)
    {
		return Cache::remember('ids.category.'.$category_id, 60, function() use ($category_id) {
			
			$ids = [$category_id];
			
			for ($i=0; $i < count($ids); $i++){
				$child_ids = Self::where('parent_id',$ids[$i])->pluck('id')->toArray();
				$ids = array_merge($ids, $child_ids);
			}
			
			return $ids;
		});
    }
    
    public function getMetaTitleAttribute()
    {
        if($this->title2){
            return str_replace(['::','br'], '-', $this->title2);
        }else{
            return $this->title;
        }
    }
    
    public function getHeaderTitleAttribute()
    {
        return '<big>'.str_replace(['::','br'], ['</big>','<br/>'], $this->title2);
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use carbon\carbon;
use App\Slugable;
use Cache;

class Post extends Model
{
    use Slugable;
    
    protected $table = 'posts';
    protected $appends = ['url','thumb','date'];
    protected $fillable = [
        'title',
        'user_id',
        'user_alias',
        'state',
        'category_id',
        'robots',
        //'text',
        'image_id',
        'header_id'
    ];
    protected $with = ['category','image'];
    protected $visible = ['id','title','url','thumb','category_id','view_count','share_count','view_avg','photo_count','video_count','date','category'];
    
    public function category()
    {
        return $this->belongsTo('App\Category');
    }	
    
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    
    public function tags()
    {
        return $this->belongsToMany('App\Tag', 'post_tag', 'post_id', 'tag_id')->withTimestamps();
    }

    public function images()
    {
        return $this->belongsToMany('App\Image', 'post_image', 'post_id', 'image_id')->withTimestamps();
    }

    public function image()
    {
        return $this->hasOne('App\Image', 'id', 'image_id');
    }

    public function header()
    {
        return $this->hasOne('App\Image', 'id', 'header_id');
    }

    public function setImageIdAttribute($value)
    {
        Image::toggleIsRelated($this->attributes['image_id'], $value);
        $this->attributes['image_id'] = $value;
    }

    public function setHeaderIdAttribute($value)
    {
        Image::toggleIsRelated($this->attributes['header_id'], $value);
        $this->attributes['header_id'] = $value;
    }
    
    public function getThumbAttribute()
    {
        if(isset($this->image->id)){
            return $this->image->url->full;
        }else{
            return url($this->image_thumb);
        }
    }

    public function getHeaderUrlAttribute()
    {
        if(isset($this->header->id)){
            return $this->header->url->full;
        }else{
            return url($this->image_full);
        }
    }
    
    public function getDateAttribute()
    {
        return $this->created_at?$this->created_at->format('d.m.Y'):'---';
    }
    
    public function getViewAvgAttribute($value)
    {
        return round($value);
    }
	
    public function scopeSearch($query, $phrase)
    {
		
		if(is_numeric($phrase)){
			return $query->where('id',$phrase);
		}
		
		$words = explode(' ',$phrase);
		
        $query->where(function ($query) use ($words) {
				$fields  = ['title','text','description','user_alias'];
				foreach($fields as $field){
					$query->orWhere(function ($query) use ($words, $field) {
						foreach($words as $word){
							$query->where($field,'LIKE','%'.$word.'%');
						}
					});
				}
			});
		
		$query->orWhereHas('user', function ($query) use ($words) {
				foreach($words as $word){
					$query->where('name','LIKE','%'.$word.'%');
				}
			});
			
		$query->orWhereHas('category', function ($query) use ($words) {
				foreach($words as $word){
					$query->where('title','LIKE','%'.$word.'%');
				}
			});
			
		return $query;
    }
    public function scopePublished($query)
    {
		$query->where('state',1)
              ->whereHas('category', function ($query) {
                    $query->where('state', 1);
              });
			
		return $query;
    } 
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Slugable;

    protected $table = 'users';
    protected $fillable = [
        'name',
        'email',
        'alias',
        'avatar_id',
        'background_id',
        'title',
        'description',
        'site',
        'without_ad'
    ];
    protected $visible = ['id', 'name'];

    public function posts()
    {
        return $this->hasMany('App\Post', 'user_id');
    }

    public function avatar()
    {
        return $this->hasOne('App\Image', 'id', 'avatar_id');
    }

    public function background()
    {
        return $this->hasOne('App\Image', 'id', 'background_id');
    }

    public function setAvatarIdAttribute($value)
    {
        Image::toggleIsRelated($this->attributes['avatar_id'] ?? 0, $value);
        $this->attributes['avatar_id'] = $value;
    }

    public function setBackgroundIdAttribute($value)
    {
        Image::toggleIsRelated($this->attributes['background_id'] ?? 0, $value);
        $this->attributes['background_id'] = $value;
    }

    public function getLogoAttribute()
    {
        if ($this->avatar) {
            return $this->avatar->url->full;
        }
    }

    public function getBackgroundOldAttribute()
    {
        if ($this->background) {
            return $this->background->url->full;
        }else{
            return url('images/users/default-background.jpg');
        }
    }
}

resources/views/category.blade.php
@extends('layouts.master', [
    'metatitle' => $category->meta_title,
    'description' => $category->description,
    'url' => $category->url,
    'image_url' => isset($posts[0]) ? $posts[0]->thumb : null,
    'robots' => true
])

@section('content')
    <div id="articles">
        @if($category->image_full)
        <div class="jumbotron jumbotron-title"{!! $category->image_full ? ' data-image="'. url($category->image_full).'"':'' !!}>
            <div class="container">
                <h1>{!! $category->header_title !!}</h1>
                <ul class="list-inline counter">
                    <li><span class="glyphicon glyphicon-eye-open"></span> 219 420</li>
                    <li><span class="glyphicon glyphicon-star-empty"></span> 282</li>
                    <li><span class="glyphicon glyphicon-thumbs-up"></span> 99</li>
                </ul>
            </div>
        </div>
        @else
        <div class="container title">
            <h1>{{ $category->title }}</h1>
        </div>
        @endif
        @if($category->text)
        <div class="container description">
            {!! $category->text !!}
        </div>
        @endif
        @include('parts.posts')
    </div>
@endsection

@push('script')
<script>
	$.post("{{ action('CountController@view')}}","id={{$category->id}}&type=Category&_token={{ csrf_token() }}");
</script>
@endpush

resources/views/index.blade.php
@extends('layouts.master', [
    'url' => url('/'),
    'robots' => true
])

@section('content')
    <div id="articles">
	@include('parts.lead')
	@include('parts.best')
	@for ($i=0; $i<=8; $i++) <?php unset($posts[$i]) ?> @endfor
	<div class="container title">
	    <h1>Полезные статьи</h1>
	</div>
	@include('parts.posts')
    </div>
@endsection

resources/views/items.blade.php
@extends('layouts.master', [
    'metatitle' => $title,
    //'description' => $category->description,
    //'url' => $category->url,
    //'image_url' => isset($posts[0]) ? $posts[0]->thumb : null,
    //'robots' => true
])

@section('content')
    <div id="articles">
	<div class="container title text-center">
	    <h1>{{ $title }}</h1>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-9">
				<div class="row">
				@foreach($items as $item)
					<div class="col-md-3 col-xs-6 mb-30">
						<a href="{{ $item->url }}" target="_blank"><img src="{{ $item->thumb }}" alt="{{ $item->title }}" title="{{ $item->title }}" class="img-responsive" /></a>
					</div>
				@endforeach
				</div>
			</div>
			<div class="col-md-3">
				<div class="list-group">
					@foreach($options_menu as $option)
					<a href="{{ route('catalog', $option->id) }}" class="list-group-item{{ $current_id==$option->id?' active':'' }}">{{ $option->title }}</a>
					@endforeach
				</div>
			</div>
		</div>
	</div>
    </div>
@endsection

resources/views/post.blade.php
@extends('layouts.master', [
    'metatitle' => $post->title . ($post->photo_count >= 5 ? (' - ' .$post->photo_count.' фото'):''),
    'description' => $post->description,
    'url' => $post->url,
    'image_url' => $post->thumb,
    'author' => $post->user_alias ? $post->user_alias : $post->user->name,
    'robots' => $post->robots,
    'body' => 'data-type="Post" data-id='.$post->id.' data-shareable=true'
])

@section('content')
<div id="article">
    <div class="jumbotron jumbotron-title"{!! $post->header_url ? ' data-image="'. url($post->header_url).'"':'' !!}>
        <div class="container">
            <h1>{{ $post->title }}</h1>
            <ul class="list-inline">
				<li title="Дата публикации">{{ $post->date }}</li>
				<li title="Число просмотров"><span class="glyphicon glyphicon-eye-open"></span> {{ $post->view_count }}</li>
				<li title="Просмотры за день"><span class="glyphicon glyphicon-star-empty"></span> {{ $post->view_avg }}</li>
				<li title="Лайки"><span class="glyphicon glyphicon-thumbs-up"></span> {{ $post->share_count }}</li>
				<li title="Количество фотографий"><span class="glyphicon glyphicon-camera"></span> {{ $post->photo_count }}</li>
				<li title="Количество видео"><span class="glyphicon glyphicon-facetime-video"></span> {{ $post->video_count }}</li>
            </ul>
			<p><a href="{{ route('slug',$post->category->alias) }}" class="category-link"># {{ $post->category->title }}</a></p>
        </div>
    </div>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="content">
					{!! $post->text !!}
					@if($post->id >= 629)
						<p class="text-center">
							Если эта статья Вам показалась интересной и полезной - ставьте лайк и делитесь ссылкой с
							друзьями - это самый простой способ сказать "спасибо"!
						</p>
						<p class="text-center">
							<img alt="Поставь лайк" src="/images/blog_03/common/Like.gif">
						</p>
					@endif
				</div>
				@if($post->user->without_ad == false)
					<div class="banner-after">
						@include('ads.g2')
					</div>
				@endif
				@include('parts.social.shares')
				<p class="tags mb-30">
					Тэги: &nbsp;
					@foreach($post->tags as $tag)
						<a href="{{ $tag->url }}"><span class="label label-default">#{{ $tag->name }}</span></a>
					@endforeach
				</p>
			</div>
			<div class="col-md-4 visible-md visible-lg text-center mb-30">
				<div class="user">
					@if($post->user_alias)
						<p>Автор: {{ $post->user_alias }}</p>
					@else
						<p>
                            <a href="{{ $post->user->url }}">
                                @if($post->user->logo)
                                    <img class="avatar-image" src="{{ $post->user->logo }}" />
                                @else
                                    <span class="avatar-char avatar-char_color_{{ $post->user->id%10 }}">{{ str_limit($post->user->name,1,'') }}</span>
                                @endif
                            </a>
						</p>
                        <p>Автор: <a href="{{ $post->user->url }}">{{ $post->user->name }}</a></p>
						@if($post->user->title)
							<p class="description small"><b>{{ $post->user->title }}</b></p>
						@endif
                        <p class="text-muted small"><a href="{{ route('users') }}">Рейтинг</a>: {{ $post->user->rating }}</p>
					@endif
				</div>
			</div>
			@if($post->user->without_ad == false)
				<div class="col-md-4 visible-md visible-lg text-center mb-30">
					@include('ads.g3')
				</div>
			@endif
			<div class="col-md-4 visible-md visible-lg">
				@include('parts.social.group')
			</div>
		</div>
	</div>
    <div class="separator"></div>
    @include('parts.related')
</div>
@endsection

@push('script')
<script>
	$.post("{{ action('CountController@view')}}","id={{$post->id}}&type=Post&_token={{ csrf_token() }}");
	$( ".ya-share2" ).on( "click", ".ya-share2__link", function() {
		$.post("{{ action('CountController@share')}}","id={{$post->id}}&type=Post&_token={{ csrf_token() }}");
	});
</script>
@endpush

resources/views/profile.blade.php
@extends('layouts.master', [
    'metatitle' => 'Мой профиль',
])

@section('content')
	<div class="container">
	    <h1>Мой профиль</h1>
        <form class="form-horizontal" method="post" action="">

            <div class="form-group">
                <label for="" class="col-sm-2 control-label" >Аватар</label>
                <div class="col-sm-8">
                    <button class="btn btn-default btn-image-upload" data-target="#profile-avatar" data-type="user_avatar"><span class="glyphicon glyphicon-plus"></span> Добавить</button>
                    <span id="profile-avatar">No photo</span>
                </div>
            </div>

            {!! csrf_field() !!}
        </form>
    </div>
@endsection

@push('script')

    <script>
        _token = '{{ csrf_token() }}';
    </script>

    <script>
        $(document).on('click', '.btn-image-upload', function(e) {
            $('#form-upload').remove();
            $('body').prepend(
                '<form enctype="multipart/form-data" id="form-upload" style="display: none;">' +
                '   <input type="file" name="upload-image" value="" data-target="'+$(this).data('target')+'" />' +
                '   <input type="hidden" name="type" value="'+$(this).data('type')+'" />' +
                '</form>'
            );
            $('#form-upload input').trigger('click');
            e.preventDefault();
        });


        $(document).delegate(':file', 'change', function () {

            var target = $(this).data('target');

            $.ajax({
                url: '/api/image?_token=' + _token,
                type: 'post',
                dataType: 'json',
                data: new FormData($('#form-upload')[0]),
                cache: false,
                contentType: false,
                processData: false,
                beforeSend: function () {
//                    $('#image-upload i').addClass('fa-circle-o-notch fa-spin');
                },
                complete: function () {
//                    $('#image-upload i').removeClass('fa-circle-o-notch fa-spin');
                },
                success: function (json) {

                    //alert(json.full);
                    $(target).html('<img src="'+json.url_thumb+'" alt="" />');

//                    if (json['error']) {
//                        alert(json['error']);
//                    }
//                    if (json['success']) {
//                        var image = {image: json.image, url: json.src, is_main: false};
//                        $('#images li:last').before(viewImage(image));
//                        renderImages();
//                    }
                },
                error: function (xhr) {
                    alert(xhr.statusText);
                }
            });
        });


    </script>
@endpush

@push('style')
    <style>

    </style>
@endpush

resources/views/search.blade.php
@extends('layouts.master',[
    'metatitle'=>'Поиск: '.$q
])

@section('content')
    <div id="articles">
	<div class="container title text-center">
	    <h1>Поиск: {{ $q }}</h1>
	</div>
	@include('parts.posts')
    </div>
@endsection

resources/views/tag.blade.php
@extends('layouts.master', [
    'metatitle' => 'Тэг: '.$tag->name,
    'robots' => $tag->alias?true:false
])

@section('content')
    <div id="articles">
	<div class="container title text-center">
	    <h1>Тэг: {{ $tag->name }}</h1>
	</div>
	@include('parts.posts')
    </div>
@endsection

resources/views/user.blade.php
@extends('layouts.master',[
    'metatitle'=>$user->name . ($user->title ? ' - '. $user->title : '').' в Мебельном журнале',
    'description' => $user->description,
    'url' => $user->url,
    'image_url' => $user->logo,
    'author' => $user->name,
    'robots' => $user->alias?true:false
])

@section('content')
	<div id="user" style="background-image: url('{{ $user->background_old }}');">
		<div class="container">
			@if($user->logo)
				<img class="avatar-image avatar-image_size_big" src="{{ $user->logo }}" />
			@else
				<span class="avatar-char avatar-char_size_middle avatar-char_color_{{ $user->id%10 }}">{{ str_limit($user->name,1,'') }}</span>
			@endif
            <h1>{{ $user->name }}</h1>
            @if($user->title)
                <p><b>{{ $user->title }}</b></p>
            @endif
			@if($user->site)
                <p class="site"><i><a href="{{ $user->site }}" target="_blank">{{ str_replace(['http://','https://'],'',$user->site) }}</a></i></p>
            @endif
            <ul class="list-inline">
				<li title="Рейтинг"><span class="glyphicon glyphicon-king"></span> {{ $user->rating }}</li>
				<li title="Число просмотров"><span class="glyphicon glyphicon-eye-open"></span> {{ $user->post_view_count }}</li>
				<li title="Просмотры за день"><span class="glyphicon glyphicon-star-empty"></span> {{ $user->view_avg }}</li>
				<li title="Понравилось"><span class="glyphicon glyphicon-thumbs-up"></span> {{ $user->share_count }}</li>
				<li title="Всех фото"><span class="glyphicon glyphicon-camera"></span> {{ $user->photo_count }}</li>
				<li title="Всех видео"><span class="glyphicon glyphicon-facetime-video"></span> {{ $user->video_count }}</li>
				<li title="Всех статей"><span class="glyphicon glyphicon-pencil"></span> {{ $user->post_count }}</li>
			</ul>
            @if($user->description)
                <p class="description">{{ $user->description }}</p>
            @endif
		</div>
	</div>
	<div id="articles">
		@include('parts.posts')
	</div>
@endsection

@push('script')
<script>
	$.post("{{ action('CountController@view')}}","id={{$user->id}}&type=User&_token={{ csrf_token() }}");
</script>
@endpush

resources/views/users.blade.php
@extends('layouts.master',[
    'metatitle'=>'Рейтинг авторов',
])

@section('content')
    <div id="users">
        <div class="container">
            <h1 class="text-center mb-30">
                Рейтинг авторов
            </h1>
            <div class="row">
                @foreach($users as $i=>$user)
                    <div class="col-xs-6 col-sm-4 col-md-2">
                        <div class="user text-center mb-30">
                            <a href="{{ $user->url }}">
                            @if($user->logo)
                                <img class="avatar-image avatar-image_size_middle mb-10" src="{{ $user->logo }}"/>
                            @else
                                <span class="avatar-char avatar-char_size_middle avatar-char_color_{{ $user->id%10 }} mb-20">{{ str_limit($user->name,1,'') }}</span>
                            @endif
                            </a>
                            <p><a href="{{ $user->url }}">{{ $user->name }}</a></p>
                            <p class="small">Рейтинг: {{ $user->rating }}</p>
                        </div>
                    </div>
                    @if (($i+1)%6==0)
                        <div class="clearfix visible-md visible-lg"></div>
                    @endif
                    @if (($i+1)%3==0)
                        <div class="clearfix visible-sm"></div>
                    @endif
                    @if (($i+1)%2==0)
                        <div class="clearfix visible-xs"></div>
                    @endif
                @endforeach
            </div>
        </div>
    </div>
@endsection