routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;

Route::get('/', 'PostsController@index')->name('main');
Route::get('search', 'PostsController@search')->name('search');
Route::get('category/{id}', 'PostsController@category')->name('category');
Route::get('user/{id}', 'PostsController@user')->name('user');
Route::get('tag/{id}', 'PostsController@tag')->name('tag');
Route::get('users', 'UsersController@index')->name('users');
Route::get('api/post', 'PostsController@api')->name('api.post');
Route::get('api/post/all', 'PostsController@all');

Route::post('api/count/view', 'CountController@view');
Route::post('api/count/share', 'CountController@share');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('api/image', 'ImageController');
    Route::get('profile', 'ProfileController@show')->name('profile');
});

Route::get('post/{id}', ['as' => 'post', 'uses' => 'PostController@show']);

Route::resource('item', 'ItemController');
Route::get('items/{ids}', ['as' => 'catalog', 'uses' => 'CatalogController@index']);

Route::get('sitemap.xml', 'XmlController@sitemap');
Route::get('sync/{subject}/{id}', ['as' => 'sync.post', 'uses' => 'SyncController@index']);

Route::get('phpinfo', ['middleware' => 'auth', 'uses' => 'Admin\UtilitiesController@phpinfo']);

Route::group(['middleware' => 'auth', 'namespace' => 'Admin', 'prefix' => 'admin'], function()
{
    Route::resource('urls', 'UrlController');
    Route::post('urls/{id}/update', 'UrlController@update')->name('admin.urls.update');
    Route::get('urls/{id}/delete', 'UrlController@destroy')->name('admin.urls.destroy');
    
    Route::resource('users', 'UserController');
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('products', 'ProductController');
    Route::resource('shops', 'ShopController');
    Route::get('shops/{id}/price', 'ShopController@priceIndex')->name('admin.shops.price');
    Route::get('shops/{id}/price/update', 'ShopController@priceUpdate')->name('admin.shops.price.update');
    Route::get('shops/{id}/price/import', 'ShopController@priceImport')->name('admin.shops.price.import');

    Route::resource('tags', 'TagController');
    Route::post('tags/{id}/update', 'TagController@update')->name('admin.tags.update');

    Route::resource('images', 'ImageController');
});

Route::get('/{slug}', ['as' => 'slug','uses' => 'SlugController@index']);

app/Shop.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Shop extends Model
{
    protected $fillable = [
        'name',
        'user_id',
        'url_yml',
        'state',
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function price()
    {
        return $this->_price ?? $this->_price = new Price($this);
    }
}

app/Http/Controllers/Admin/ShopController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Shop;
use App\User;

class ShopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Shop::with('user')->orderBy('id','desc')->paginate(30);
        return view('admin.shop.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Shop;
        $users = User::orderBy('id','desc')->pluck('name', 'id');
        return view('admin.shop.create',compact('model','users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $model = Shop::create($request->all());
        return redirect($request->input('return'))->with('message', 'Категория <b>'.$model->title.'</b> сохранена!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Shop::findOrFail($id);
        $users = User::orderBy('id','desc')->pluck('name', 'id');
        return view('admin.shop.edit',compact('model','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Shop::findOrFail($id);
        $model->update($request->all());
        return redirect($request->input('return'))->with('message', 'Категория <b>'.$model->title.'</b> сохранена!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function priceIndex($id)
    {
        $shop = Shop::findOrFail($id);
        return view('admin.shop.price',compact('shop'));
    }

    public function priceUpdate(Request $request, $id)
    {
        Shop::findOrFail($id)->price()->load();
        return redirect($request->input('return'))->with('message', 'Прайс скопирован на сервер. Теперь его можно импортировать');
    }

    public function priceImport(Request $request, $id)
    {
        $count = Shop::findOrFail($id)->price()->import();
        return redirect($request->input('return'))->with('message', 'Импортированно <b>'.$count.'</b> товаров');
    }
}

resources/views/admin/shop/create.blade.php
@extends('layouts.master',[
    'metatitle'=>'Создать магазин',
])

@section('content')
	<div class="container">
	    <h1>Создать магазин</h1>
		@include('admin.shop.form', [
		    			'action' => route('admin.shops.store'),
		    			'method' => 'POST',
		    		])
	</div>
@endsection

@push('style')
    <link href="{{ elixir('css/admin.css') }}" rel="stylesheet"/>
@endpush

resources/views/admin/shop/edit.blade.php
@extends('layouts.master',[
    'metatitle'=>'Редактировать магазин',
])

@section('content')
	<div class="container">
	    <h1>Редактировать магазин</h1>
		@include('admin.shop.form', [
		    			'action' => route('admin.shops.update',$model->id),
		    			'method' => 'PUT',
		    		])
	</div>
@endsection

@push('style')
    <link href="{{ elixir('css/admin.css') }}" rel="stylesheet"/>
@endpush

resources/views/admin/shop/form.blade.php
{!! Form::open(['url' => $action, 'class'=>'form-horizontal', 'method' => $method]) !!}
	@foreach($model->getFillable() as $name)
		@if($name == 'state')
            <div class="form-group">
                {!! Form::label($name, null, ['class'=>'col-sm-2 control-label']) !!}
                <div class="col-sm-8">
                    {!! Form::select($name, [0 => 'Не опубликовано', 1 => 'Опубликовано'], $model->{$name}, ['class'=>'form-control']) !!}
                </div>
            </div>
        @elseif($name == 'user_id')
            <div class="form-group">
                {!! Form::label($name, null, ['class'=>'col-sm-2 control-label']) !!}
                <div class="col-sm-8">
                    {!! Form::select($name, $users->prepend('Не выбрано', 0), $model->{$name}, ['class'=>'form-control']) !!}
                </div>
            </div>
		@else
			<div class="form-group">
                {!! Form::label($name, null, ['class'=>'col-sm-2 control-label']) !!}
				<div class="col-sm-8">
                    {!! Form::text($name, $model->{$name}, ['id' => $name,'class'=>'form-control']) !!}
				</div>
			</div>
		@endif
	@endforeach
    @include('form.buttons')
{!! Form::close() !!}

resources/views/admin/shop/index.blade.php
@extends('layouts.master',[
    'metatitle'=>'Магазины',
])

@section('content')
	<div class="container">
        <div class="row">
            <div class="col-md-10">
                <h1>Магазины <span class="badge">{{ $data->total() }}</span></h1>
            </div>
            <div class="col-md-2 btn-admin-group">
                <a class="btn btn-default btn-block" href="{{ route('admin.shops.create',array('return'=>URL::full())) }}"><span class="glyphicon glyphicon-plus"></span> Создать</a>
            </div>
        </div>
        <table class="table table-bordered table-hover table-striped">
		<tr>
            <th>id</th>
		    <th>Название</th>
		    <th>Пользователь</th>
		    <th>Активность</th>
            <th width="10"></th>
            <th width="10"></th>
            <th width="10"></th>
		</tr>
		@foreach($data as $model)
		<tr>
            <td>{{ $model->id }}</td>
		    <td>{{ $model->name }}</td>
            <td>@if($model->user){{ $model->user->name }}@endif</td>
            <td>@if(!$model->state)Не активен@endif</td>
            <td><a href="{{ route("admin.products.index",['shop_id'=>$model->id]) }}">Товары</a></td>
            <td><a href="{{ route('admin.shops.price',array('id'=>$model->id, 'return'=>URL::full())) }}">Прайс</a></td>
            <td><a href="{{ route('admin.shops.edit',array('id'=>$model->id, 'return'=>URL::full())) }}"><span class="glyphicon glyphicon-edit"></span></a></td>
		</tr>
		@endforeach
	    </table>
        <div class="text-center">
            {{ $data->render() }}
        </div>
	</div>
@endsection

@push('style')
<link href="{{ elixir('css/admin.css') }}" rel="stylesheet"/>
@endpush

resources/views/admin/shop/price.blade.php
@extends('layouts.master',[
    'metatitle'=>'Магазины',
])

@section('content')
	<div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Прайс: {{ $shop->name }} <span class="badge">{{ $shop->price()->totalProducts() }}</span></h1>
            </div>
            <div class="col-md-5 btn-admin-group">
                <div class="btn-group btn-group-justified">
                    <div class="btn-group">
                        <a class="btn btn-default btn-block" href="{{ Request::input('return') }}"><span class="glyphicon glyphicon-arrow-left"></span> Отмена</a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-default btn-block" href="{{ route('admin.shops.price.update',array('id'=>$shop->id, 'return'=>URL::full())) }}"><span class="glyphicon glyphicon-refresh"></span> Обновить</a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-default btn-block" href="{{ route('admin.shops.price.import',array('id'=>$shop->id, 'return'=>URL::full())) }}"><span class="glyphicon glyphicon-import"></span> Импорт</a>
                    </div>
                </div>
            </div>
        </div>
        <table class="table table-bordered table-hover table-striped">
		<tr>
            <th>id</th>
		    <th>Название</th>
		    <th>Цена</th>
		    <th width="100"></th>
		</tr>
		@foreach($shop->price()->products() as $product)
		<tr>
            <td>{{ $product->id }}</td>
            <td><a href="{{ $product->image }}" class="gallery-item">{{ $product->name }}</a></td>
            <td>{{ $product->price }}</td>
            <td><a href="{{ $product->url }}" target="_blank">В магазин</a></td>
		</tr>
		@endforeach
	    </table>
	</div>
@endsection

@push('style')
<link href="{{ elixir('css/admin.css') }}" rel="stylesheet"/>
@endpush