routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;

Route::get('/', 'PostsController@index')->name('main');
Route::get('search', 'PostsController@search')->name('search');
Route::get('category/{id}', 'PostsController@category')->name('category');
Route::get('user/{id}', 'PostsController@user')->name('user');
Route::get('tag/{id}', 'PostsController@tag')->name('tag');
Route::get('users', 'UsersController@index')->name('users');
Route::get('api/post', 'PostsController@api')->name('api.post');
Route::get('api/post/all', 'PostsController@all');

Route::post('api/count/view', 'CountController@view');
Route::post('api/count/share', 'CountController@share');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('api/image', 'ImageController');
    Route::get('profile', 'ProfileController@show')->name('profile');
});

Route::get('post/{id}', ['as' => 'post', 'uses' => 'PostController@show']);

Route::resource('item', 'ItemController');
Route::get('items/{ids}', ['as' => 'catalog', 'uses' => 'CatalogController@index']);

Route::get('sitemap.xml', 'XmlController@sitemap');
Route::get('sync/{subject}/{id}', ['as' => 'sync.post', 'uses' => 'SyncController@index']);

Route::get('phpinfo', ['middleware' => 'auth', 'uses' => 'Admin\UtilitiesController@phpinfo']);

Route::group(['middleware' => 'auth', 'namespace' => 'Admin', 'prefix' => 'admin'], function()
{
    Route::resource('urls', 'UrlController');
    Route::post('urls/{id}/update', 'UrlController@update')->name('admin.urls.update');
    Route::get('urls/{id}/delete', 'UrlController@destroy')->name('admin.urls.destroy');
    
    Route::resource('users', 'UserController');
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('products', 'ProductController');
    Route::resource('shops', 'ShopController');
    Route::get('shops/{id}/price', 'ShopController@priceIndex')->name('admin.shops.price');
    Route::get('shops/{id}/price/update', 'ShopController@priceUpdate')->name('admin.shops.price.update');
    Route::get('shops/{id}/price/import', 'ShopController@priceImport')->name('admin.shops.price.import');

    Route::resource('tags', 'TagController');
    Route::post('tags/{id}/update', 'TagController@update')->name('admin.tags.update');

    Route::resource('images', 'ImageController');
});

Route::get('/{slug}', ['as' => 'slug','uses' => 'SlugController@index']);

resources/views/parts/best.blade.php
<div class="best">
    <h1>Самые читаемые <span class="glyphicon glyphicon-fire"></span></h1>
    <div class="container">
	<div class="row">
	    <div class="owl-carousel">
	    @if($posts)
		@foreach($posts as $post)
			@include('parts.post')
		@endforeach
	    @endif
	    </div>
	</div>
    </div>
    <div class="owl-buttons">
	<a href="#" class="owl-prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
	<a href="#"  class="owl-next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>
    <div class="banner">
	@include('ads.g1')
    </div>
</div>

resources/views/parts/business.blade.php
<div class="cover">
	<div class="header">
		<a href="{{ \App\Category::url(100) }}">Мебельный бизнес</a>
	</div>
	@if($posts)
	    @foreach($posts as $post)
		<article>
		    <div class="date">
			{{ $post->date }}
		    </div>
		    <div class="title">
			<a href="{{ $post->url }}">{{ $post->title }}</a>
		    </div>
		</article>
	    @endforeach
	@endif
	<div class="more">
		<a href="{{ \App\Category::url(100) }}">Ещё статьи о мебельном бизнесе</a>
	</div>
</div>

resources/views/parts/categories.blade.php
<ul class="list-inline">
    @foreach($categories as $category)
    <li>
        <a href="{{ $category['url'] }}" class="btn btn-default">{{ $category['title'] }}</a>
    </li>
    @endForeach
    <li>
        <a href="{{ \App\Category::url(100) }}" class="btn btn-default">Мебельный бизнес</a>
    </li>
</ul>

resources/views/parts/counters.blade.php
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter548335 = new Ya.Metrika({id:548335, clickmap:true, trackLinks:true, accurateTrackBounce:true, params:window.yaParams||{ }});
                w.yaCounter548335 = new Ya.Metrika({id:34263960, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, params:window.yaParams||{ }});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/548335" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<noscript><div><img src="//mc.yandex.ru/watch/34263960" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-12104784-2', 'auto');
  ga('send', 'pageview');

</script>

resources/views/parts/items.blade.php
@if($title)
	<h3><span class="hidden-xs">Смотрите также: </span><a href=http://palmiramebel.ru/items.html?{{ $select }}>{{ $title }}</a></h3>
@endif
<div class="slider row">
@foreach($items as $item)
	<div class="col-md-3 col-xs-6">
	<a href="{{ $item->url }}" class="item" target="_blank"><img src="{{ $item->thumb }}" alt="{{ $item->title }}" title="{{ $item->title }}" /></a>
	</div>
@endforeach
</div>

resources/views/parts/lead.blade.php
<div class="container lead_items">
    <div class="row">
	@include('parts.post', [
	    'post' => $posts[0],
	    'class'=>'col-md-8 col-lg-6 style1-md style1-lg',
	])
	@include('parts.post', [
	    'post' => $posts[1],
	    'class'=>'col-md-4 col-lg-3 hidden-md style2-lg',
	    'view_intro'=>true,
	])
	<div class="col-md-4 col-lg-3 visible-md visible-lg">
	    @include('ads.send')
	</div>
	<div class="clearfix visible-md visible-lg"></div>
	@include('parts.post', [
	    'post'=>$posts[2],
	    'class'=>'col-md-4 col-lg-3 style2-md style2-lg',
	    'view_intro'=>true,
	])
	@include('parts.post', [
	    'post'=>$posts[3],
	    'class'=>'col-md-4 col-lg-6 style1-lg style2-md',
	])
	<div class="col-md-4 col-lg-3 business">
	    @include('parts.business')
	</div>
	<div class="clearfix visible-md visible-lg"></div>
	<?php for ($i=4; $i<=6; $i++) { ?>
	@include('parts.post', [
	    'post'=>$posts[$i],
	    'class'=>'col-lg-3 col-md-4',
	])
	<?php } ?>
	@include('parts.post', [
	    'post'=>$posts[7],
	    'class'=>'col-md-4 col-lg-3 hidden-md',
	    'view_intro'=>true,
	])
    </div>
</div>

resources/views/parts/nav.blade.php
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
	<div class="navbar-header">
	    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	    </button>
	    <span class="hidden-md hidden-lg">
		<a class="btn navbar-btn btn-link pull-right" href="/send.html"><span class="glyphicon glyphicon-edit"></span><span class="hidden-xs"> Добавить</span></a>
		<a class="btn btn-link navbar-btn pull-right" href="#searchbar" data-toggle="collapse"><span class="glyphicon glyphicon-search"></span></a>
	    </span>
	    <a class="navbar-brand" href="{{ url('/') }}" >Мебельный <span>журнал</span></a>
	</div>
	<div id="navbar" class="collapse navbar-collapse">
	    <ul class="nav navbar-nav">
		<li class="dropdown">
		    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Категории<b class="caret"></b></a>
		    <div class="dropdown-menu navbar-menu">
		    @include('parts.categories')
		    </div>
		</li>
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Онлайн конструкторhh <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><a href="https://kitchen.prodboard.com/SR_85c532c24af444d797a58855b3848192_0019/STANDART" target="_blank">Кухня</a></li>
				<li><a href="https://kitchen.prodboard.com/SR_85c532c24af444d797a58855b3848192_0019/VMNY" target="_blank">Шкаф-купе</a></li>
			</ul>
		</li>
	    </ul>
	    <ul class="nav navbar-nav navbar-right hidden-xs hidden-sm">
		<li><a href="#searchbar" data-toggle="collapse"><span class="glyphicon glyphicon-search"></span> Поиск</a></li>
	    </ul>
	    <ul class="nav navbar-nav navbar-right hidden-md">
	    @if (Auth::guest())
		<li>
			<a href="{{ route('login') }}"><span class="glyphicon glyphicon-log-in"></span> Войти</a>
		</li>
	    @else
		<li class="dropdown">
		    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> {{ Auth::user()->name }} <b class="caret"></b></a>
		    <ul class="dropdown-menu">
                <li><a href="{{ action("Admin\UrlController@index") }}"><span class="glyphicon glyphicon-link"></span>&nbsp; Ссылки</a></li>
                <li><a href="{{ route("admin.users.index") }}"><span class="glyphicon glyphicon-user"></span>&nbsp; Пользователи</a></li>
                <li><a href="{{ route("admin.posts.index") }}"><span class="glyphicon glyphicon-file"></span>&nbsp; Посты</a></li>
                <li><a href="{{ route("admin.categories.index") }}"><span class="glyphicon glyphicon-folder-open"></span>&nbsp; Категории</a></li>
                <li><a href="{{ route("admin.tags.index") }}"><span class="glyphicon glyphicon-tags"></span>&nbsp; Тэги</a></li>
                <li><a href="{{ route("admin.images.index") }}"><span class="glyphicon glyphicon-picture"></span>&nbsp; Изображения</a></li>
                <li><a href="{{ route("admin.shops.index") }}"><span class="glyphicon glyphicon-shopping-cart"></span>&nbsp; Магазины</a></li>
                <li><a href="{{ route("admin.products.index") }}"><span class="glyphicon glyphicon-lamp"></span>&nbsp; Товары</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ action("Auth\AuthController@logout") }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp; Выход</a></li>
		    </ul>
		</li>
	    @endif
	    </ul>
	    <a class="btn navbar-btn btn-primary btn-sm pull-right hidden-xs hidden-sm" href="{{ \App\Post::url(624) }}"><span class="glyphicon glyphicon-file"></span> Добавить</a>
	</div>
    </div>
</nav>
<nav id="searchbar" class="navbar navbar-default navbar-fixed-top collapse">
    <div class="container">
	<p class="navbar-text hidden-xs">Поиск по сайту</p>	
	<a href="#searchbar" class="close" data-toggle="collapse">&times;</a>
	<form class="navbar-form" role="search" action="{{ route('search') }}">
	    <div class="input-group">
		<input type="text" class="form-control" placeholder="Поиск" name="q" value="{{ request()->input('q') }}">
		<span class="input-group-btn">
			<button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-search"></span></button>
		</span>
	    </div>
	</form>
    </div>
</nav>

resources/views/parts/post.blade.php
<article class="{{ $class ?? 'default' }}">
    <div class="image">
	<a href="{{ $post->url }}"><img src="{{ $post->thumb }}" alt="{{ $post->title }}" class="img-responsive"></a>
    </div>
    <div class="text">
	<ul class="list-inline details">
	    <li>{{ $post->date }}</li>
	    <li><span class="glyphicon glyphicon-eye-open"></span> {{ $post->view_count }}</li>
	    <li><span class="glyphicon glyphicon-star-empty"></span> {{ $post->view_avg }}</li>
	    <li><span class="glyphicon glyphicon-thumbs-up"></span> {{ $post->share_count }}</li>
	    <li><span class="glyphicon glyphicon-camera"></span> {{ $post->photo_count }}</li>
	</ul>
	<div class="title">
	    <a href="{{ $post->url }}">{{ $post->title }}</a>
	</div>
	@if(isset($view_intro) and $view_intro)
	<div class="intro">
	    {{ $post->description }}
	</div>
	@endIf
    </div>
    <div class="category">
	<a href="{{ $post->category->url }}" class="category-link">{{ $post->category->title }}</a>
    </div>		
</article>

resources/views/parts/posts.blade.php
<div class="container items">
    @if(count($posts))
    <div class="row">
	@foreach($posts as $i=>$post)
	    @include('parts.post', ['class'=>'col-md-4'])
	@if (($i+1)%3==0)
	<div class="clearfix visible-md visible-lg"></div>
	@endif
	@endForeach
    </div>
    @else
    <div class="alert alert-warning alert-dismissable">
	По вашему запросу ничего не нашлось
    </div>
    @endif
</div>
@if($posts->lastPage()>1)
<div class="text-center">
    <button id="load" class="btn btn-default btn-posts mb-30" data-url="{{ $next_page_url }}" data-loading-text="Загружается...">Показать ещё</button>
</div>
@endif
<div class="banner">
@include('ads.g1')
</div>

@push('script')
<script>
    jQuery(document).ready(function($) {
	jQuery(document).on('click','#load', function(){
	    var btn = $(this);
	    btn.button('loading')
	    $.ajax({
		url: btn.data('url'),
		dataType: "json",
		success: function(json){
		    json.data.forEach(function(post,i){
			html =	'<article class="col-md-4">'+
				'   <div class="image">'+
				'	<a href="'+post.url+'"><img src="'+post.thumb+'" alt="'+post.title+'" class="img-responsive"></a>'+
				'   </div>'+
				'   <div class="text">'+
				'	<ul class="list-inline details">'+
				'	    <li>'+post.date+'</li>'+
				'	    <li><span class="glyphicon glyphicon-eye-open"></span> '+post.view_count+'</li>'+
				'	    <li><span class="glyphicon glyphicon-star-empty"></span> '+post.view_avg+'</li>'+
				'	    <li><span class="glyphicon glyphicon-thumbs-up"></span> '+post.share_count+'</li>'+
				'	    <li><span class="glyphicon glyphicon-camera"></span> '+post.photo_count+'</li>'+
				'	</ul>'+
				'	<div class="title">'+
				'	    <a href="'+post.url+'">'+post.title+'</a>'+
				'	</div>'+
				'   </div>'+
				'   <div class="category">'+
				'	<a href="'+post.category.url+'" class="category-link">'+post.category.title+'</a>'+
				'   </div>'+
				'</article>';
			if ((i+1)%3==0){
			    html = html + '<div class="clearfix visible-md visible-lg"></div>';
			}
			$(".container.items .row").append(html);
		    });
		    console.log(json);
		    btn.data('url',json.next_page_url)
		    btn.button('reset');
		    if(btn.data('url') == null){
			btn.hide();
		    }
		}
	    });
	});
    });
</script>
@endpush

resources/views/parts/related.blade.php
<div class="articles">
    <div class="container">
	<div class="h3">Читайте также:</div>
	<div class="row">
	    @foreach($posts as $i => $post)
		<article class="col-md-4">
		    <div class="image">
			<a href="{{ $post->url }}"><img src="{{ $post->thumb }}" class="img-responsive" /></a>
		    </div>
		    <div class="text">
			<div class="title">
				<a href="{{ $post->url }}">{{ $post->title }}</a>
			</div>
			<div class="category">
			    <a href="{{ route('slug',$post->category->alias) }}" class="category-link">{{ $post->category->title }}</a>
			</div>
		    </div>
		</article>
		@if (($i+1)%3==0)
		<div class="clearfix visible-md visible-lg"></div>
		@endif
	    @endforeach
	</div>
    </div>
</div>

resources/views/parts/youtube.blade.php
<p class="youtube">
<iframe src="https://www.youtube.com/embed/{{ $video_id }}" frameborder="0" allowfullscreen></iframe>
</p>