routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;

Route::get('/', 'PostsController@index')->name('main');
Route::get('search', 'PostsController@search')->name('search');
Route::get('category/{id}', 'PostsController@category')->name('category');
Route::get('user/{id}', 'PostsController@user')->name('user');
Route::get('tag/{id}', 'PostsController@tag')->name('tag');
Route::get('users', 'UsersController@index')->name('users');
Route::get('api/post', 'PostsController@api')->name('api.post');
Route::get('api/post/all', 'PostsController@all');

Route::post('api/count/view', 'CountController@view');
Route::post('api/count/share', 'CountController@share');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('api/image', 'ImageController');
    Route::get('profile', 'ProfileController@show')->name('profile');
});

Route::get('post/{id}', ['as' => 'post', 'uses' => 'PostController@show']);

Route::resource('item', 'ItemController');
Route::get('items/{ids}', ['as' => 'catalog', 'uses' => 'CatalogController@index']);

Route::get('sitemap.xml', 'XmlController@sitemap');
Route::get('sync/{subject}/{id}', ['as' => 'sync.post', 'uses' => 'SyncController@index']);

Route::get('phpinfo', ['middleware' => 'auth', 'uses' => 'Admin\UtilitiesController@phpinfo']);

Route::group(['middleware' => 'auth', 'namespace' => 'Admin', 'prefix' => 'admin'], function()
{
    Route::resource('urls', 'UrlController');
    Route::post('urls/{id}/update', 'UrlController@update')->name('admin.urls.update');
    Route::get('urls/{id}/delete', 'UrlController@destroy')->name('admin.urls.destroy');
    
    Route::resource('users', 'UserController');
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('products', 'ProductController');
    Route::resource('shops', 'ShopController');
    Route::get('shops/{id}/price', 'ShopController@priceIndex')->name('admin.shops.price');
    Route::get('shops/{id}/price/update', 'ShopController@priceUpdate')->name('admin.shops.price.update');
    Route::get('shops/{id}/price/import', 'ShopController@priceImport')->name('admin.shops.price.import');

    Route::resource('tags', 'TagController');
    Route::post('tags/{id}/update', 'TagController@update')->name('admin.tags.update');

    Route::resource('images', 'ImageController');
});

Route::get('/{slug}', ['as' => 'slug','uses' => 'SlugController@index']);

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Slugable;

    protected $table = 'users';
    protected $fillable = [
        'name',
        'email',
        'alias',
        'avatar_id',
        'background_id',
        'title',
        'description',
        'site',
        'without_ad'
    ];
    protected $visible = ['id', 'name'];

    public function posts()
    {
        return $this->hasMany('App\Post', 'user_id');
    }

    public function avatar()
    {
        return $this->hasOne('App\Image', 'id', 'avatar_id');
    }

    public function background()
    {
        return $this->hasOne('App\Image', 'id', 'background_id');
    }

    public function setAvatarIdAttribute($value)
    {
        Image::toggleIsRelated($this->attributes['avatar_id'] ?? 0, $value);
        $this->attributes['avatar_id'] = $value;
    }

    public function setBackgroundIdAttribute($value)
    {
        Image::toggleIsRelated($this->attributes['background_id'] ?? 0, $value);
        $this->attributes['background_id'] = $value;
    }

    public function getLogoAttribute()
    {
        if ($this->avatar) {
            return $this->avatar->url->full;
        }
    }

    public function getBackgroundOldAttribute()
    {
        if ($this->background) {
            return $this->background->url->full;
        }else{
            return url('images/users/default-background.jpg');
        }
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('rating','desc')->paginate(30);
        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User;
        return view('admin.user.create',compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->input('email') == '' or $request->input('email') == ''){
            return redirect()->back()->with('error', 'E-mail и Имя пользователя обязательны!');
        }

        if(User::whereEmail($request->input('email'))->count()){
            return redirect()->back()->with('error', 'Такой E-mail уже есть');
        }

        $user = User::create($request->all());
        return redirect($request->input('return'))->with('message', 'Пользователь <b>'.$user->name.'</b> сохранён!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('admin.user.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $user->update($request->all());
        return redirect($request->input('return'))->with('message', 'Пользователь <b>'.$user->name.'</b> сохранён!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\User;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::Where('post_count','>',' 0')->orderBy('rating','desc')->get();
        return view('users',compact('users'));
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.master',[
    'metatitle'=>'Создать пользователя',
])

@section('content')
	<div class="container">
	    <h1>Создать пользователя</h1>
		@include('admin.user.form', [
		    			'action' => route('admin.users.store'),
		    			'method' => 'POST',
		    		])
	</div>
@endsection

@push('style')
    <link href="{{ elixir('css/admin.css') }}" rel="stylesheet"/>
@endpush

resources/views/admin/user/edit.blade.php
@extends('layouts.master',[
    'metatitle'=>'Редактировать Пользователя',
])

@section('content')
	<div class="container">
	    <h1>Редактировать пользователя</h1>
		@include('admin.user.form', [
		    			'action' => route('admin.users.update',$user->id),
		    			'method' => 'PUT',
		    		])
	</div>
@endsection

@push('style')
    <link href="{{ elixir('css/admin.css') }}" rel="stylesheet"/>
@endpush

resources/views/admin/user/form.blade.php
<form class="form-horizontal" action="{{$action}}" method="POST" enctype="multipart/form-data">
	@if($method == 'PUT')
		<input name="_method" type="hidden" value="PUT">
	@endif
	@foreach($user->getFillable() as $name)
		@if($name == 'description')
			<div class="form-group">
				<label for="{{ $name }}" class="col-sm-2 control-label" title="state">{{ $name }}</label>
				<div class="col-sm-8">
					<textarea class="form-control" id="{{ $name }}" name="{{ $name }}" rows="3">{{ $user->{$name} }}</textarea>
				</div>
			</div>
		@elseif($name == 'without_ad')
			<div class="form-group">
				<label for="{{ $name }}" class="col-sm-2 control-label" title="state">{{ $name }}</label>
				<div class="col-sm-8">
					<select class="form-control" name="{{ $name }}">
						@foreach(['Отображать рекламу'=>0,'Без рекламы'=>1] as $label => $value)
							<option value="{{ $value }}"{{ $value == $user->{$name}?'selected="selected"':'' }}>{{ $label }}</option>
						@endforeach
					</select>
				</div>
			</div>
		@elseif($name == 'avatar_id')
			@include('form.image',['key'=>'avatar_id','id'=>$user->avatar_id,'image'=>$user->avatar,'type'=>'user_avatar'])
		@elseif($name == 'background_id')
			@include('form.image',['key'=>'background_id','id'=>$user->background_id,'image'=>$user->background,'type'=>'user_background'])
		@else
			<div class="form-group">
				<label for="{{ $name }}" class="col-sm-2 control-label" title="state">{{ $name }}</label>
				<div class="col-sm-8">
				  <input type="text" class="form-control" id="{{ $name }}" name="{{ $name }}" value="{{ $user->{$name} }}">
				</div>
			</div>
		@endif
	@endforeach
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<div class="btn-group">
				<a class="btn btn-default" href="{{ Request::input('return') }}"><span class="glyphicon glyphicon-arrow-left"></span> Отмена</a>
				<button type="submit" class="btn btn-default" name="return" value="{{ Request::input('return') }}"><span class="glyphicon glyphicon-floppy-disk"></span> Сохранить</button>
				@if($method == 'PUT')
				<button type="submit" class="btn btn-default" name="return" value="{{ URL::full() }}"><span class="glyphicon glyphicon-refresh"></span> Обновить</button>
				@endif
			</div>
		</div>
	</div>
	{!! csrf_field() !!}
</form>

@push('script')
<script>
    _token = '{{ csrf_token() }}';
</script>
<script src="{{ elixir('js/admin.js') }}" type="text/javascript"></script>
@endpush

resources/views/admin/user/index.blade.php
@extends('layouts.master',[
    'metatitle'=>'Пользователи',
])

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-10">
				<h1>Пользователи <span class="badge">{{ $users->total() }}</span></h1>
			</div>
			<div class="col-md-2 btn-admin-group">
				<a class="btn btn-default btn-block" href="{{ route('admin.users.create',array('return'=>URL::full())) }}"><span class="glyphicon glyphicon-plus"></span> Создать</a>
			</div>
		</div>
	    <table class="table table-bordered table-hover table-striped">
		<tr>
            <th class="text-center">id</th>
		    <th width="50">Фото</th>
		    <th>Имя</th>
		    <th class="text-center"><span class="glyphicon glyphicon-star-empty"></span></th>
            <th class="text-center"><span class="glyphicon glyphicon-thumbs-up"></span></th>
            <th class="text-center"><span class="glyphicon glyphicon-eye-open"></span></th>
            <th class="text-center"><span class="glyphicon glyphicon-pencil"></span></th>
            <th class="text-center"><span class="glyphicon glyphicon-camera"></span></th>
            <th class="text-center"><span class="glyphicon glyphicon-facetime-video"></span></th>
		    <th>Почта</th>
		    <th width="10"></th>
		</tr>
		@foreach($users as $user)
		<tr>
			<td align="right">{{ $user->id }}</td>
			<td>@if($user->avatar)<img src="{{ $user->avatar->url->small  }}" alt="" />@endif</td>
			<td>
                <a href="{{ $user->url }}" target="_blank">{{ $user->name }}</a>
                <div class="small text-muted">
                    {{ $user->alias }}
                </div>
            </td>
		    <td align="right">{{ $user->rating }}</td>
            <td align="right">{{ $user->share_count }}</td>
            <td align="right">{{ $user->view_avg }}</td>
            <td align="right">{{ $user->post_count }}</td>
            <td align="right">{{ $user->photo_count }}</td>
            <td align="right">{{ $user->video_count }}</td>
		    <td>{{ $user->email }}</td>
            <td><a href="{{ route('admin.users.edit',array('id'=>$user->id, 'return'=>URL::full())) }}"><span class="glyphicon glyphicon-edit"></span></a></td>
		</tr>
		@endforeach
	    </table>
        <div class="text-center">
            {{ $users->render() }}
        </div>
	</div>
@endsection

@push('style')
<link href="{{ elixir('css/admin.css') }}" rel="stylesheet"/>
@endpush